import type { Metadata } from 'next';
import LegalPageLayout, { type Para } from '@/components/legal/legal-page-layout';

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description: 'How Wiley Fox collects, uses, and protects your personal data.',
};

const CONTENT: Para[] = [
  { style: "Normal", text: `Last updated: 4 August 2026 Version: 1.1 Applies to: the Wiley Fox mobile application, thewileyfox.com, our QR-linked products, and all related services (together, the "Services").` },
  { style: "Heading2", text: `1. Who we are and how to reach us` },
  { style: "Normal", text: `Wiley Fox is operated by Wiley Fox Mapping Limited ("Wiley Fox", "we", "us", "our"), a company registered in England and Wales.` },
  { style: "Normal", text: `Company number` },
  { style: "Normal", text: `17172765` },
  { style: "Normal", text: `Registered office` },
  { style: "Normal", text: `[19 Hereford Close, Hook,United Kingdom]` },
  { style: "Normal", text: `ICO registration number` },
  { style: "Normal", text: `[ ZC143718 ]` },
  { style: "Normal", text: `Privacy contact` },
  { style: "Normal", text: `privacy@thewileyfox.com` },
  { style: "Normal", text: `General contact` },
  { style: "Normal", text: `admin@thewileyfox.com` },
  { style: "Normal", text: `EU representative (Art. 27 UK/EU GDPR)` },
  { style: "Normal", text: `[Barry Wilson]` },
  { style: "Normal", text: `We are the data controller for the personal data described in this policy, including data about Protected Persons (see section 7).` },
  { style: "Normal", text: `If you are unhappy with how we handle your data you can complain to us first at privacy@thewileyfox.com. You also have the right to complain to the Information Commissioner's Office (ico.org.uk, 0303 123 1113) or to your local supervisory authority.` },
  { style: "Heading2", text: `2. The short version` },
  { style: "Normal", text: `We think you should be able to understand what we do with your data without a law degree. In summary:` },
  { style: "Normal", text: `We collect the minimum we need. Especially for children's data and health data.` },
  { style: "Normal", text: `Nothing sensitive is shared without your explicit, specific consent. You choose what goes on a QR tag. You choose whether a photo can be broadcast. You can change your mind at any time.` },
  { style: "Normal", text: `We never sell your personal data for money, to anyone, ever. The free tier does show ads, and to do that we share a resettable advertising identifier with our ad partner — which some US state laws treat as "sharing". You can turn it off. Section 13 explains it plainly, and we never advertise to under-18s using their data.` },
  { style: "Normal", text: `Safety information in the app is provided for information only. It comes largely from third-party public sources and from other users. We do not verify it and we do not guarantee it. Please read section 9 carefully.` },
  { style: "Normal", text: `Wiley Fox is not an emergency service. In an emergency, always contact the local emergency services first.` },
  { style: "Normal", text: `The full detail follows. Where a section particularly matters — children, health data, SOS — we have flagged it.` },
  { style: "Heading2", text: `3. Who can use Wiley Fox` },
  { style: "Normal", text: `You must be at least 16 years old to hold your own Wiley Fox account.` },
  { style: "Normal", text: `In limited circumstances, a person aged 13 to 15 may hold a linked account, but only where:` },
  { style: "Normal", text: `a parent or legal guardian has created a Family Group and provided verifiable consent; and` },
  { style: "Normal", text: `local law in the user's country permits it; and` },
  { style: "Normal", text: `the account is restricted to reduced functionality (no public community broadcasting, no independent SOS sharing outside the Family Group).` },
  { style: "Normal", text: `We do not knowingly create accounts for anyone under 13, anywhere in the world. This includes users in the United States, where the Children's Online Privacy Protection Act (COPPA) applies.` },
  { style: "Normal", text: `Children of any age may be included as a Protected Person on a guardian's account — for example, a child linked to a QR tag or wristband. A Protected Person does not hold an account, does not agree to our terms, and their data is managed entirely by their guardian. See section 7.` },
  { style: "Normal", text: `If we learn that we hold data for an account holder under the permitted age, we will delete that account and its data without undue delay. If you believe a child's data is held incorrectly, contact privacy@thewileyfox.com and we will act within 72 hours.` },
  { style: "Heading2", text: `4. What we collect` },
  { style: "Heading3", text: `4.1 Information you give us` },
  { style: "Normal", text: `Category` },
  { style: "Normal", text: `Examples` },
  { style: "Normal", text: `Why we need it` },
  { style: "Normal", text: `Account data` },
  { style: "Normal", text: `Name, email address, password (hashed), phone number, country, date of birth or age band` },
  { style: "Normal", text: `To create and secure your account, verify age eligibility` },
  { style: "Normal", text: `Profile data` },
  { style: "Normal", text: `Display name, profile photo, language, notification preferences` },
  { style: "Normal", text: `To personalise the Services` },
  { style: "Normal", text: `Family Group data` },
  { style: "Normal", text: `Names and relationships of Family Group members, linked Protected Persons` },
  { style: "Normal", text: `To operate Family Groups, SOS alerting and QR tag reunification` },
  { style: "Normal", text: `Protected Person data` },
  { style: "Normal", text: `A child's or dependant's first name, age, photograph, distinguishing details, emergency contacts` },
  { style: "Normal", text: `To help reunite a lost person with their guardian` },
  { style: "Normal", text: `Health and medical data` },
  { style: "Normal", text: `Allergies, conditions, medications, blood type, emergency contacts, care instructions` },
  { style: "Normal", text: `Only if you choose to add it to a medical QR profile` },
  { style: "Normal", text: `User-generated content` },
  { style: "Normal", text: `Safety pins, area reports, reviews, photographs, comments, messages sent through the app` },
  { style: "Normal", text: `To operate the community safety features` },
  { style: "Normal", text: `Purchase data` },
  { style: "Normal", text: `Delivery address, order history, subscription tier` },
  { style: "Normal", text: `To fulfil merchandise orders and manage subscriptions` },
  { style: "Normal", text: `Support data` },
  { style: "Normal", text: `Correspondence with us, reports of misuse, appeals` },
  { style: "Normal", text: `To provide support and enforce our terms` },
  { style: "Heading3", text: `4.2 Information we collect automatically` },
  { style: "Normal", text: `Category` },
  { style: "Normal", text: `Examples` },
  { style: "Normal", text: `Location data` },
  { style: "Normal", text: `Precise GPS location (only with your permission and only while relevant features are in use); approximate location derived from IP address` },
  { style: "Normal", text: `Device and technical data` },
  { style: "Normal", text: `Device model, operating system, app version, device identifiers, crash logs, IP address, time zone` },
  { style: "Normal", text: `Usage data` },
  { style: "Normal", text: `Screens viewed, features used, searches, session length, referring links` },
  { style: "Normal", text: `QR scan data` },
  { style: "Normal", text: `Time, approximate location and device type of each scan of one of your QR tags; the scanner's message to you if they choose to send one` },
  { style: "Normal", text: `Cookies and similar technologies` },
  { style: "Normal", text: `See section 13` },
  { style: "Heading3", text: `4.3 Information from third parties` },
  { style: "Normal", text: `Public crime and safety data — including data.police.uk (UK Home Office), national statistics agencies, and other public sources catalogued in our data register.` },
  { style: "Normal", text: `Payment providers — confirmation of payment status. We do not receive or store your full card number.` },
  { style: "Normal", text: `Affiliate and booking partners — confirmation that a booking was made through our link, for commission reconciliation. We do not receive your full booking details.` },
  { style: "Normal", text: `App stores — subscription status and receipt validation.` },
  { style: "Normal", text: `Fraud and abuse prevention providers — signals used to detect misuse of the Services.` },
  { style: "Heading3", text: `4.4 Data we deliberately do not collect` },
  { style: "Normal", text: `We do not collect your precise location in the background when you are not using a location-dependent feature. We do not collect contacts from your phone unless you explicitly invite someone. We do not collect biometric data, and we do not run facial recognition or face matching on any photograph.` },
  { style: "Normal", text: `We never use any of the following for advertising, in any circumstances: your precise or historical location, your health or medical data, Protected Person data, Child Alert content, the contents of your QR tags, SOS data, or anything you have marked private. See section 13 for what advertising on the free tier does involve.` },
  { style: "Heading3", text: `4.5 Photographs — metadata is removed` },
  { style: "Normal", text: `Photographs normally carry hidden metadata, including the exact GPS coordinates and time the picture was taken. We strip all location and device metadata from every image on upload, before it is stored or shown to anyone. A photograph you upload will not reveal where it was taken unless you separately choose to attach a location.` },
  { style: "Heading2", text: `5. Our legal bases for using your data (UK & EU GDPR)` },
  { style: "Normal", text: `What we do` },
  { style: "Normal", text: `Legal basis` },
  { style: "Normal", text: `Create and operate your account` },
  { style: "Normal", text: `Contract (Art. 6(1)(b))` },
  { style: "Normal", text: `Fulfil merchandise orders and subscriptions` },
  { style: "Normal", text: `Contract (Art. 6(1)(b))` },
  { style: "Normal", text: `Display crime, safety and mapping information` },
  { style: "Normal", text: `Legitimate interests — providing the core service (Art. 6(1)(f))` },
  { style: "Normal", text: `Process precise location for maps, routing and SOS` },
  { style: "Normal", text: `Consent (Art. 6(1)(a)), given via your device permission` },
  { style: "Normal", text: `Store and share health / medical data on a medical QR profile` },
  { style: "Normal", text: `Explicit consent (Art. 6(1)(a) and Art. 9(2)(a))` },
  { style: "Normal", text: `Share health data where you are physically or legally incapable of consenting` },
  { style: "Normal", text: `Vital interests (Art. 6(1)(d) and Art. 9(2)(c))` },
  { style: "Normal", text: `Store and share a child's photograph or details for reunification` },
  { style: "Normal", text: `Explicit consent of the guardian (Art. 6(1)(a) and, where the data is special category, Art. 9(2)(a)); vital interests where the child is at immediate risk` },
  { style: "Normal", text: `Broadcast a lost-person or lost-item alert to the community` },
  { style: "Normal", text: `Explicit consent (Art. 6(1)(a)) — you opt in each time` },
  { style: "Normal", text: `Send SOS alerts to your Family Group` },
  { style: "Normal", text: `Contract and vital interests` },
  { style: "Normal", text: `Security, fraud prevention, abuse detection, enforcing our terms` },
  { style: "Normal", text: `Legitimate interests (Art. 6(1)(f)) and legal obligation (Art. 6(1)(c))` },
  { style: "Normal", text: `Analytics and product improvement` },
  { style: "Normal", text: `Consent where required, otherwise legitimate interests` },
  { style: "Normal", text: `Show and measure advertising on the free tier` },
  { style: "Normal", text: `Consent (Art. 6(1)(a)). Never applied to under-18 accounts — see section 13` },
  { style: "Normal", text: `Marketing emails` },
  { style: "Normal", text: `Consent, or soft opt-in for existing customers. Unsubscribe at any time` },
  { style: "Normal", text: `Responding to law enforcement or court orders` },
  { style: "Normal", text: `Legal obligation (Art. 6(1)(c))` },
  { style: "Normal", text: `Where we rely on consent, you can withdraw it at any time in the app under Settings → Privacy, or by emailing privacy@thewileyfox.com. Withdrawing consent does not affect processing carried out before you withdrew it, and may mean a feature stops working.` },
  { style: "Normal", text: `Where we rely on legitimate interests, we have carried out a balancing assessment. You can request a summary of it, and you have the right to object (see section 14).` },
  { style: "Heading2", text: `6. QR-linked products: lost items, lost children, and medical wristbands` },
  { style: "Normal", text: `This section describes the most sensitive data we handle. Please read it in full.` },
  { style: "Heading3", text: `6.1 How QR tags work` },
  { style: "Normal", text: `You can attach a Wiley Fox QR tag — a sticker, keyring, luggage tag, clothing label or wristband — to an item, a child, or yourself. When someone scans it, they see a web page containing only the information you have chosen to publish for that tag, and nothing else.` },
  { style: "Normal", text: `You control, per tag:` },
  { style: "Normal", text: `what information is displayed;` },
  { style: "Normal", text: `whether a photograph is displayed;` },
  { style: "Normal", text: `whether the finder can send you a message;` },
  { style: "Normal", text: `whether the finder can see any medical information;` },
  { style: "Normal", text: `whether the tag is active at all.` },
  { style: "Normal", text: `You can change or deactivate any tag at any time, instantly, from the app. Deactivating a tag takes effect immediately — a subsequent scan will show only a "this tag is not active" message.` },
  { style: "Heading3", text: `6.2 Lost item tags` },
  { style: "Normal", text: `A scan of an item tag shows only what you have set — typically a first name and a contact route. We recommend not publishing your home address. When someone scans your tag, we record the time, the approximate location and the device type of the scan, and we notify you. The scanner's own precise location is only shared with you if they actively choose to share it.` },
  { style: "Heading3", text: `6.3 Child tags — additional protections` },
  { style: "Normal", text: `Where a tag is linked to a Protected Person under 18, additional safeguards apply:` },
  { style: "Normal", text: `Only a person with parental responsibility or legal guardianship may create the tag. You must confirm this when you register the child, and you warrant to us that it is true.` },
  { style: "Normal", text: `A child's photograph is never displayed by default. Displaying a photograph requires a separate, explicit, recorded opt-in by the guardian.` },
  { style: "Normal", text: `A child's medical information is never displayed by default. It requires a separate explicit opt-in, and can be restricted to "on request only", where the scanner must ask and you must approve in the moment.` },
  { style: "Normal", text: `We never publish a child's surname, home address, school, or date of birth on a scan page.` },
  { style: "Normal", text: `The scanner is shown a notice reminding them that they are viewing a child's data, that misuse is a criminal offence in many jurisdictions, and that they should contact the local police or emergency services if the child is at risk.` },
  { style: "Normal", text: `All scans of a child tag are logged and shown to the guardian.` },
  { style: "Normal", text: `Location metadata is stripped from every photograph on upload (section 4.5), so a child's picture can never reveal where it was taken.` },
  { style: "Normal", text: `Scan pages cannot be found, guessed or crawled. Every tag has a long, randomly generated address that cannot be worked out from another tag's. Scan pages carry noindex instructions so search engines do not list them, and we rate-limit and monitor attempts to try addresses at scale.` },
  { style: "Heading3", text: `6.4 Child Alerts and community lost-person broadcasts` },
  { style: "Normal", text: `If a child or dependant is lost, a guardian may choose to raise a Child Alert — a pin on the map, plus a notification to other Wiley Fox users in the surrounding area.` },
  { style: "Normal", text: `A guardian raising a Child Alert for their own child is the only circumstance in which an image of a child may appear anywhere on Wiley Fox. Our Terms prohibit every other posting of a child's image, and we screen every uploaded image. See Terms clause 5.7.` },
  { style: "Normal", text: `This is opt-in, every single time. Consent given at sign-up is not sufficient on its own; the guardian must confirm the broadcast at the moment it is sent, and confirm what is included.` },
  { style: "Normal", text: `The guardian chooses whether the photograph is included, and can raise an alert without one.` },
  { style: "Normal", text: `The photograph is never displayed automatically. A user must actively tap through a warning notice before it is revealed. The notice explains that the image shows a missing child, that it may be used only to help find them, and that any other use may be a criminal offence.` },
  { style: "Normal", text: `Every reveal is logged — who viewed it and when — and the log is available to the guardian and to the police.` },
  { style: "Normal", text: `The photograph is removed from the Services the instant the guardian cancels the alert, and automatically on expiry.` },
  { style: "Normal", text: `The alert contains the minimum necessary: a description, an approximate area, a time, and a route to contact you or the police. It does not contain your home address or the child's full identifying details.` },
  { style: "Normal", text: `The guardian can cancel the broadcast at any time, and we will withdraw it from the app. We cannot recall copies that other users have already saved, screenshotted or shared outside the app. Please consider this before broadcasting a photograph.` },
  { style: "Normal", text: `We will automatically expire a broadcast after [24] hours unless renewed.` },
  { style: "Normal", text: `Broadcasting to the community is never a substitute for contacting the police. The app will prompt you to contact the emergency services first.` },
  { style: "Heading3", text: `6.5 Medical wristbands and medical QR profiles` },
  { style: "Normal", text: `Health data is special category data under UK and EU GDPR and we treat it accordingly.` },
  { style: "Normal", text: `A medical profile is created only by you (or, for a Protected Person, by their guardian), and only with explicit consent recorded at the point of entry.` },
  { style: "Normal", text: `You decide exactly which fields are visible on a scan. Nothing you have not selected is ever shown. There is no hidden data behind a medical scan page.` },
  { style: "Normal", text: `Medical information is displayed to a scanner only in the context of assisting you. The scan page carries a notice that the data is provided for emergency assistance only and that any other use may be unlawful.` },
  { style: "Normal", text: `We log every scan of a medical tag and make the log visible to you.` },
  { style: "Normal", text: `Where you are unconscious or otherwise incapable of consenting, we may rely on vital interests to display the information you previously chose to publish.` },
  { style: "Normal", text: `Wiley Fox is not a medical device, a medical service, or a substitute for professional medical care. We do not verify, interpret or update medical information. It is your responsibility to keep it accurate.` },
  { style: "Heading3", text: `6.6 SOS alerts` },
  { style: "Normal", text: `If you trigger an SOS:` },
  { style: "Normal", text: `Your alert and your location are sent to your Family Group by default.` },
  { style: "Normal", text: `You may additionally choose to share the alert with nearby Wiley Fox users in the local community. Where local community sharing is enabled by default in your settings, you can turn it off at any time before or during an alert, and we will tell you clearly at set-up that it is on.` },
  { style: "Normal", text: `Only the information necessary to get help to you is shared: an approximate or precise location (your choice), a first name, and any emergency information you have chosen to include. Your address, full identity, account details and unrelated medical data are not shared.` },
  { style: "Normal", text: `SOS alerts and their location trails are retained for [90] days and then deleted, unless you ask us to keep a record or we are required to retain it.` },
  { style: "Normal", text: `Wiley Fox is not an emergency service. An SOS alert does not contact the police, ambulance, coastguard, mountain rescue or any other emergency service. It depends on a working internet connection, a charged device, and other people choosing to respond. It may fail. Always contact the local emergency services first — 999 in the UK, 112 across the EU and much of the world, 911 in the US.` },
  { style: "Heading2", text: `7. Family Groups, guardians and Protected Persons` },
  { style: "Normal", text: `A Family Group Administrator (usually a parent or guardian) can add other members and Protected Persons.` },
  { style: "Normal", text: `When you add a Protected Person, you are giving us their personal data. You confirm that you have the legal authority to do so and, where the person is capable of understanding, that you have explained it to them in a way they can understand.` },
  { style: "Normal", text: `Where a child is aged 13 or over, we encourage guardians to involve them in decisions about their own data, and we will present child-facing explanations in age-appropriate language.` },
  { style: "Normal", text: `Members of a Family Group can see the location and status information that the Group's settings permit. Each member aged 16+ can review and object to what is shared about them.` },
  { style: "Normal", text: `A Protected Person, or someone acting for them, can ask us to remove their data at any time by contacting privacy@thewileyfox.com, even if the guardian objects. We will assess the request in the person's best interests.` },
  { style: "Normal", text: `In relation to Protected Person data, the guardian decides what is published and to whom. We remain the controller for that data, because we design and determine how the tag, scan page and alert systems work, and we process it for our own purposes of safety, security, abuse prevention and legal compliance. We say this openly rather than describe ourselves as a mere processor, because it means the responsibility for protecting a child's data sits with us and not only with the parent.` },
  { style: "Heading3", text: `Safeguarding` },
  { style: "Normal", text: `If we become aware of credible evidence that the Services are being used to harm, stalk, groom or endanger a child or vulnerable adult, we may suspend the account and disclose relevant information to the police or a relevant safeguarding authority without notifying the account holder. We consider this necessary in the vital interests of the person at risk and in our legitimate interest in preventing serious harm.` },
  { style: "Heading3", text: `Image screening and child sexual abuse material` },
  { style: "Normal", text: `Every image uploaded to Wiley Fox is automatically screened before it is published, to detect child sexual abuse material and images of children posted in breach of our Terms. Screening is automated; a human reviews only where the system flags something or a user reports it.` },
  { style: "Normal", text: `Where we identify child sexual abuse material, or content that appears to constitute grooming or child sexual exploitation, we will — without notifying the account holder, and without waiting for a report — remove it, permanently ban the accounts involved, preserve the material and the associated account, device, location and log data as evidence, and report it to the police, to the Internet Watch Foundation, and to the National Center for Missing & Exploited Children where there is a US connection. We will cooperate fully with any investigation.` },
  { style: "Normal", text: `We rely on substantial public interest — preventing or detecting unlawful acts (UK GDPR Art. 9(2)(g) and Schedule 1 Part 2 of the Data Protection Act 2018), legal obligation, and the vital interests of children at risk. This processing is not subject to your right to erasure or objection, and we will not confirm or discuss a report with the person who is the subject of it.` },
  { style: "Heading3", text: `Our duties under the Online Safety Act 2023` },
  { style: "Normal", text: `Wiley Fox is a user-to-user service. We carry out and keep under review an illegal content risk assessment and a children's risk assessment, operate the reporting and complaints routes described in our Terms, and keep records of our safety decisions, as required by the Act and by Ofcom.` },
  { style: "Heading2", text: `8. Contact, blocking and misuse` },
  { style: "Normal", text: `When someone scans your tag, they may be able to send you a message. To protect you:` },
  { style: "Normal", text: `Your email address and phone number are never revealed to a scanner. Messages are relayed through Wiley Fox.` },
  { style: "Normal", text: `You can block any user or scanner permanently, at any time, with one action. A blocked person cannot contact you again through the Services, including via a different tag.` },
  { style: "Normal", text: `We retain a limited record of blocked interactions for safety and abuse-prevention purposes, even after you block.` },
  { style: "Normal", text: `You can report a scanner or user. We investigate reports and may suspend or ban accounts, and where appropriate report matters to the police.` },
  { style: "Normal", text: `Using a Wiley Fox QR tag or the community features to track, harass, stalk, intimidate or defraud another person is strictly prohibited, is grounds for immediate permanent ban, and may be a criminal offence.` },
  { style: "Heading2", text: `9. Mapping, crime data and community safety information` },
  { style: "Normal", text: `This section explains an important limitation. Please read it.` },
  { style: "Normal", text: `Wiley Fox displays crime statistics, safety ratings, area information, routes and user-submitted reports.` },
  { style: "Normal", text: `This information is provided for general information only. It is not advice, a recommendation, an assurance, or a prediction.` },
  { style: "Normal", text: `We do not generate the underlying crime data. It comes from third-party public sources such as data.police.uk and equivalent national bodies. It is often incomplete, delayed by weeks or months, inconsistently categorised between regions, and reflects only reported crime.` },
  { style: "Normal", text: `We do not fact-check user-submitted pins, reports, photographs or reviews. They are the opinions and observations of individual users. They may be inaccurate, out of date, biased or malicious.` },
  { style: "Normal", text: `A safety rating is a calculated indicator, not a guarantee. An area rated as safer is not safe. Serious harm can and does occur in areas with low recorded crime.` },
  { style: "Normal", text: `We do not recommend, endorse or vouch for any place, route, region or country. If you choose to travel somewhere, or take a particular route, you do so entirely at your own risk and on your own judgement.` },
  { style: "Normal", text: `Always check official sources — for UK travellers, the FCDO travel advice at gov.uk/foreign-travel-advice; and equivalent government advice in your own country — and use your own judgement.` },
  { style: "Normal", text: `The full legal position on this is set out in our Terms & Conditions.` },
  { style: "Heading2", text: `10. Who we share your data with` },
  { style: "Normal", text: `We share personal data only as described here. We do not sell personal data, and we do not share it with third parties for their own marketing.` },
  { style: "Normal", text: `Recipient` },
  { style: "Normal", text: `What they receive` },
  { style: "Normal", text: `Why` },
  { style: "Normal", text: `Other users` },
  { style: "Normal", text: `Only what you publish or broadcast: tag content, community pins, SOS alerts you have chosen to share` },
  { style: "Normal", text: `To operate the community features` },
  { style: "Normal", text: `Hosting and infrastructure (e.g. Supabase, Netlify, cloud storage)` },
  { style: "Normal", text: `Data at rest and in transit` },
  { style: "Normal", text: `To run the Services` },
  { style: "Normal", text: `Payment processors (e.g. Stripe, Apple, Google)` },
  { style: "Normal", text: `Payment and subscription data. We never see your full card number` },
  { style: "Normal", text: `To take payment` },
  { style: "Normal", text: `Merchandise fulfilment / print-on-demand partners` },
  { style: "Normal", text: `Name, delivery address, order contents` },
  { style: "Normal", text: `To make and ship your order` },
  { style: "Normal", text: `Email and notification providers` },
  { style: "Normal", text: `Email address, device push token` },
  { style: "Normal", text: `To send service messages` },
  { style: "Normal", text: `Analytics and crash reporting` },
  { style: "Normal", text: `Pseudonymised usage and diagnostic data` },
  { style: "Normal", text: `To fix bugs and improve the product` },
  { style: "Normal", text: `Advertising partner (free tier only)` },
  { style: "Normal", text: `A resettable advertising identifier, approximate region, app context. Never location history, health, children's or Protected Person data` },
  { style: "Normal", text: `To show and measure ads on the free tier. Not used for under-18 accounts — see section 13` },
  { style: "Normal", text: `Affiliate and booking partners (e.g. Booking.com)` },
  { style: "Normal", text: `A referral identifier only. We do not pass your name or contact details` },
  { style: "Normal", text: `To attribute a booking and reconcile commission` },
  { style: "Normal", text: `Mapping and tile providers` },
  { style: "Normal", text: `Requests for map tiles, which contain approximate location` },
  { style: "Normal", text: `To render maps` },
  { style: "Normal", text: `Professional advisers (lawyers, accountants, auditors)` },
  { style: "Normal", text: `As necessary, under duty of confidentiality` },
  { style: "Normal", text: `Legal and financial compliance` },
  { style: "Normal", text: `Police, emergency services, safeguarding authorities` },
  { style: "Normal", text: `Relevant information` },
  { style: "Normal", text: `Vital interests, safeguarding, legal obligation` },
  { style: "Normal", text: `A buyer of our business` },
  { style: "Normal", text: `Data may transfer as part of a merger, acquisition or asset sale` },
  { style: "Normal", text: `Business continuity. We will notify you` },
  { style: "Normal", text: `All processors are bound by written contracts requiring them to act only on our instructions, to keep data secure, and to delete or return it at the end of the engagement.` },
  { style: "Normal", text: `A current, named list of our sub-processors is published at thewileyfox.com/legal/subprocessors and updated when it changes.` },
  { style: "Heading3", text: `Third-party bookings` },
  { style: "Normal", text: `If you follow a link to book accommodation, an attraction or an activity, you leave Wiley Fox and enter into a contract with that provider, under their terms and their privacy policy. We are not a party to that contract and we do not control their data practices. We earn a commission on some bookings; this never increases the price you pay and never affects the safety information we show you.` },
  { style: "Heading2", text: `11. International transfers` },
  { style: "Normal", text: `Wiley Fox is available worldwide, so your data may be transferred to and processed in countries outside the UK and the European Economic Area, including the United States.` },
  { style: "Normal", text: `Where we transfer personal data out of the UK or EEA, we rely on one of the following safeguards:` },
  { style: "Normal", text: `UK adequacy regulations or an EU adequacy decision for the destination country;` },
  { style: "Normal", text: `the UK International Data Transfer Agreement (IDTA) or the UK Addendum to the EU Standard Contractual Clauses;` },
  { style: "Normal", text: `the EU Standard Contractual Clauses (2021/914);` },
  { style: "Normal", text: `certification under the UK–US Data Bridge / EU–US Data Privacy Framework, where the recipient is certified.` },
  { style: "Normal", text: `We carry out a transfer risk assessment before making a restricted transfer, and apply additional technical measures — including encryption in transit and at rest — where the assessment requires it. You can request a copy of the relevant safeguard by emailing privacy@thewileyfox.com.` },
  { style: "Heading2", text: `12. How long we keep data` },
  { style: "Normal", text: `Data` },
  { style: "Normal", text: `Retention` },
  { style: "Normal", text: `Account data` },
  { style: "Normal", text: `For as long as your account is active, then [30] days after deletion` },
  { style: "Normal", text: `Protected Person data` },
  { style: "Normal", text: `Until removed by the guardian, or the account is deleted, then [30] days` },
  { style: "Normal", text: `Medical profile data` },
  { style: "Normal", text: `Until you delete it or close your account, then deleted immediately from live systems and within [30] days from backups` },
  { style: "Normal", text: `QR scan logs` },
  { style: "Normal", text: `[12] months` },
  { style: "Normal", text: `SOS alerts and location trails` },
  { style: "Normal", text: `[90] days` },
  { style: "Normal", text: `Community broadcasts and Child Alerts` },
  { style: "Normal", text: `Expired after [24] hours; record retained [90] days` },
  { style: "Normal", text: `Child Alert image reveal logs` },
  { style: "Normal", text: `[12] months, or longer where the police ask us to preserve them` },
  { style: "Normal", text: `Advertising identifier and ad interaction data` },
  { style: "Normal", text: `[13] months, or until you opt out or subscribe to Premium` },
  { style: "Normal", text: `Material reported as child sexual abuse, and associated evidence` },
  { style: "Normal", text: `Preserved as directed by law enforcement; not deleted on request` },
  { style: "Normal", text: `User-generated content (pins, reviews)` },
  { style: "Normal", text: `Until you delete it, or the account is deleted. Anonymised aggregate safety signals may be retained` },
  { style: "Normal", text: `Purchase and transaction records` },
  { style: "Normal", text: `6 years from the end of the relevant tax year (UK statutory requirement)` },
  { style: "Normal", text: `Support correspondence` },
  { style: "Normal", text: `[3] years` },
  { style: "Normal", text: `Abuse, ban and safeguarding records` },
  { style: "Normal", text: `[6] years, or longer where necessary to protect others` },
  { style: "Normal", text: `Marketing consent records` },
  { style: "Normal", text: `[6] years after withdrawal, as evidence of consent` },
  { style: "Normal", text: `Backups` },
  { style: "Normal", text: `Rolling [35] day cycle, after which deleted data is permanently unrecoverable` },
  { style: "Normal", text: `When we no longer need data we delete it or irreversibly anonymise it.` },
  { style: "Heading2", text: `13. Cookies, similar technologies and advertising` },
  { style: "Heading3", text: `13.1 Cookies and storage` },
  { style: "Normal", text: `Our website and app use:` },
  { style: "Normal", text: `Strictly necessary cookies and storage — for login, security and basic function. These do not require consent.` },
  { style: "Normal", text: `Functional storage — remembering your preferences.` },
  { style: "Normal", text: `Analytics — understanding how the Services are used.` },
  { style: "Normal", text: `Advertising identifiers and storage on the free tier — see 13.2.` },
  { style: "Normal", text: `On first visit we ask for your consent to non-essential cookies via a banner, and you can change your choice at any time at thewileyfox.com/legal/cookies or in Settings → Privacy. We honour Global Privacy Control (GPC) signals where your browser sends one.` },
  { style: "Heading3", text: `13.2 Advertising on the free tier` },
  { style: "Normal", text: `Wiley Fox has a free tier and a paid tier. The free tier is supported by advertising. Premium is completely ad-free.` },
  { style: "Normal", text: `To show ads on the free tier we share a resettable advertising identifier (your device's IDFA on iOS or Advertising ID on Android), your approximate country or region, and basic app-context signals with our advertising partner. We do this so that advertising can be measured and, if you allow it, made more relevant.` },
  { style: "Normal", text: `What we never share with advertisers, under any circumstances:` },
  { style: "Normal", text: `your precise or historical location;` },
  { style: "Normal", text: `your health or medical data, or anything on a medical QR profile;` },
  { style: "Normal", text: `any Protected Person's data, photograph or details;` },
  { style: "Normal", text: `any Child Alert, SOS alert, or the content of either;` },
  { style: "Normal", text: `the contents of your QR tags, your Family Group, or your private messages;` },
  { style: "Normal", text: `your name, email address or phone number.` },
  { style: "Normal", text: `Your controls:` },
  { style: "Normal", text: `On iOS we ask for App Tracking Transparency permission. If you decline, you still get the app in full — you simply see non-personalised ads instead.` },
  { style: "Normal", text: `On Android and the web you can opt out at Settings → Privacy → Advertising, or reset your advertising ID in your device settings.` },
  { style: "Normal", text: `Subscribing to Premium removes advertising entirely.` },
  { style: "Normal", text: `Declining or opting out never reduces your access to any safety feature.` },
  { style: "Normal", text: `Legal basis: consent (Art. 6(1)(a)), given through the ATT prompt, the cookie banner or the in-app control. You can withdraw it at any time.` },
  { style: "Heading3", text: `13.3 Children and advertising` },
  { style: "Normal", text: `We do not run personalised or behavioural advertising to anyone we know or believe to be under 18.` },
  { style: "Normal", text: `Accounts held by 13–15 year-olds within a Family Group are set to contextual advertising only, permanently. This cannot be switched on, by them or by anyone else.` },
  { style: "Normal", text: `We do not profile children, build advertising audiences from them, or pass any child's identifier to an advertising partner.` },
  { style: "Normal", text: `We do not use nudge techniques to encourage any user, and particularly any child, to weaken their privacy settings.` },
  { style: "Normal", text: `This reflects our commitment to the ICO's Age Appropriate Design Code (Children's Code).` },
  { style: "Heading2", text: `14. Your rights` },
  { style: "Normal", text: `Under UK and EU GDPR you have the right to:` },
  { style: "Normal", text: `Right` },
  { style: "Normal", text: `What it means` },
  { style: "Normal", text: `Access` },
  { style: "Normal", text: `Get a copy of the personal data we hold about you` },
  { style: "Normal", text: `Rectification` },
  { style: "Normal", text: `Have inaccurate data corrected` },
  { style: "Normal", text: `Erasure` },
  { style: "Normal", text: `Have your data deleted ("right to be forgotten")` },
  { style: "Normal", text: `Restriction` },
  { style: "Normal", text: `Have us pause processing while a dispute is resolved` },
  { style: "Normal", text: `Portability` },
  { style: "Normal", text: `Receive your data in a machine-readable format, or have it sent to another provider` },
  { style: "Normal", text: `Object` },
  { style: "Normal", text: `Object to processing based on legitimate interests, and to direct marketing (which we will always stop)` },
  { style: "Normal", text: `Withdraw consent` },
  { style: "Normal", text: `At any time, for anything based on consent` },
  { style: "Normal", text: `Not be subject to solely automated decisions` },
  { style: "Normal", text: `We do not make decisions with legal or similarly significant effects about you by automated means` },
  { style: "Normal", text: `How to exercise them: in the app under Settings → Privacy → My Data (which offers self-service export and deletion), or by emailing privacy@thewileyfox.com.` },
  { style: "Normal", text: `We respond within one month. We may extend by two further months for complex requests, and will tell you if we do. There is no charge unless a request is manifestly unfounded or excessive.` },
  { style: "Heading3", text: `If you are in the United States` },
  { style: "Normal", text: `Depending on your state (including California, Colorado, Connecticut, Virginia, Utah, Texas and others), you may also have the right to know what personal information we collect, to delete it, to correct it, to opt out of "sale" or "sharing" and of targeted advertising, to limit use of sensitive personal information, and not to be discriminated against for exercising these rights.` },
  { style: "Normal", text: `We do not sell personal information for money. However, on the free tier we share a resettable advertising identifier with our advertising partner so that ads can be shown and measured. Under the CCPA/CPRA this is treated as "sharing" for cross-context behavioural advertising, and we disclose it as such rather than rely on a technicality.` },
  { style: "Normal", text: `You can opt out at Settings → Privacy → Advertising, by declining the App Tracking Transparency prompt on iOS, via our "Do Not Sell or Share My Personal Information" link, or by sending a Global Privacy Control signal, which we honour automatically.` },
  { style: "Normal", text: `We never share sensitive personal information — health data, precise geolocation, or children's data — for advertising or for any cross-context behavioural purpose. This limits our use of sensitive personal information to what CCPA permits without a separate right to limit.` },
  { style: "Normal", text: `We do not share the personal information of any user under 18 for advertising, and we do not knowingly sell or share the personal information of anyone under 16. Premium subscribers see no advertising at all.` },
  { style: "Normal", text: `To exercise your rights, email privacy@thewileyfox.com or use the in-app controls. You may use an authorised agent. We will verify your identity before acting.` },
  { style: "Heading3", text: `If you are elsewhere` },
  { style: "Normal", text: `We apply the standards in this policy globally as our baseline, and comply with additional local requirements where they apply — including Canada (PIPEDA), Australia (Privacy Act), Brazil (LGPD) and others.` },
  { style: "Heading2", text: `15. How we protect your data` },
  { style: "Normal", text: `Encryption in transit (TLS 1.2+) and at rest (AES-256).` },
  { style: "Normal", text: `Medical and Protected Person data is stored with additional access restrictions and field-level protection.` },
  { style: "Normal", text: `Row-level security so a user's data is only ever accessible to that user and their authorised Family Group.` },
  { style: "Normal", text: `Access control — staff access is role-based, minimal, logged, and reviewed. Very few people can access production data, and never medical data without a logged, justified reason.` },
  { style: "Normal", text: `Multi-factor authentication available on all accounts and required for staff.` },
  { style: "Normal", text: `Regular security testing, dependency scanning and patching.` },
  { style: "Normal", text: `Breach response — if a personal data breach is likely to result in a risk to your rights and freedoms, we will notify the ICO within 72 hours and, where the risk is high, notify you without undue delay.` },
  { style: "Normal", text: `No system is perfectly secure. Please use a strong, unique password and enable multi-factor authentication.` },
  { style: "Heading2", text: `16. Changes to this policy` },
  { style: "Normal", text: `We will update this policy from time to time. If we make a material change — for example a new category of data, a new purpose, or a new class of recipient — we will:` },
  { style: "Normal", text: `give you at least 30 days' notice by email and in-app before it takes effect; and` },
  { style: "Normal", text: `where the change relies on consent, ask for your consent afresh rather than assuming it.` },
  { style: "Normal", text: `Previous versions are archived at thewileyfox.com/legal/archive.` },
  { style: "Heading2", text: `17. Contact` },
  { style: "Normal", text: `Privacy queries, data subject requests and complaints: privacy@thewileyfox.com` },
  { style: "Normal", text: `Wiley Fox Mapping Limited, [19 Hereford close, Hook, United Kingdom]` },
  { style: "Normal", text: `Information Commissioner's Office — ico.org.uk · 0303 123 1113 · Wycliffe House, Water Lane, Wilmslow, Cheshire SK9 5AF` },
  { style: "Normal", text: `Wiley Fox helps you travel with more confidence. It cannot make you safe. Please use it alongside your own judgement, official advice, and the emergency services.` },
];

export default function PrivacyPolicyPage() {
  return (
    <LegalPageLayout
      title="Privacy Policy"
      lastUpdated="4 August 2026"
      version="1.1"
      applies={`Applies to: the Wiley Fox mobile application, thewileyfox.com, our QR-linked products, and all related services (together, the "Services").`}
      content={CONTENT}
      otherLink={{ href: '/terms', label: 'Terms & Conditions' }}
    />
  );
}
