import type { Metadata } from 'next';
import LegalPageLayout, { type Para } from '@/components/legal/legal-page-layout';

export const metadata: Metadata = {
  title: 'Terms & Conditions',
  description: 'The legal agreement between you and Wiley Fox Mapping Limited.',
};

const CONTENT: Para[] = [
  { style: "Normal", text: `Last updated: 4 August 2026 Version: 1.1` },
  { style: "Heading2", text: `Please read this first` },
  { style: "Normal", text: `These Terms are a legal agreement between you and Wiley Fox Mapping Limited. By creating an account, scanning a Wiley Fox QR tag, buying our products, or using our app or website, you agree to them.` },
  { style: "Normal", text: `Five things we need you to understand before you go any further:` },
  { style: "Normal", text: `1. Wiley Fox is not an emergency service. An SOS alert does not contact the police, ambulance or any other emergency service. In an emergency, call the local emergency number — 999 in the UK, 112 in the EU and much of the world, 911 in the US.` },
  { style: "Normal", text: `2. We do not promise that anywhere is safe. Our maps, crime data and safety ratings are information, not advice or assurance. A high safety rating does not mean you will be safe. Serious harm occurs in low-crime areas. Where you go, and how, is your decision and your risk.` },
  { style: "Normal", text: `3. We do not fact-check what other users post. Pins, reports, photos and reviews are the views of individual users. They may be wrong, out of date, or deliberately misleading.` },
  { style: "Normal", text: `4. QR tags and medical wristbands are aids, not guarantees. They depend on a stranger choosing to scan them, on a working internet connection, and on the information you entered being accurate. They will not always work.` },
  { style: "Normal", text: `5. You must never post an image of a child. The only exception is a child in your own Family Group, during an active Child Alert that you have raised as their guardian. Posting any other image of an identifiable child is a serious breach of these Terms and will result in an immediate permanent ban. Clause 5.7 sets this out in full and you must accept it separately before you can post any image.` },
  { style: "Normal", text: `If you do not accept these Terms, please do not use the Services.` },
  { style: "Heading2", text: `1. Definitions` },
  { style: "Normal", text: `Term` },
  { style: "Normal", text: `Meaning` },
  { style: "Normal", text: `"Wiley Fox", "we", "us", "our"` },
  { style: "Normal", text: `Wiley Fox Mapping Limited, registered in England and Wales, company number 17172765, registered office [19 Hereford close,Hook,United Kingdom]` },
  { style: "Normal", text: `"You", "your"` },
  { style: "Normal", text: `The person agreeing to these Terms` },
  { style: "Normal", text: `"Services"` },
  { style: "Normal", text: `The Wiley Fox mobile app, thewileyfox.com, QR tag scan pages, and all related features` },
  { style: "Normal", text: `"Products"` },
  { style: "Normal", text: `Physical goods we sell — QR stickers, keyrings, luggage tags, clothing labels, wristbands and similar` },
  { style: "Normal", text: `"Content"` },
  { style: "Normal", text: `Anything you submit — pins, reports, photographs, reviews, messages, profile and tag information` },
  { style: "Normal", text: `"Safety Information"` },
  { style: "Normal", text: `Crime data, safety ratings, area information, routes and related material displayed in the Services` },
  { style: "Normal", text: `"Family Group"` },
  { style: "Normal", text: `A linked set of accounts and Protected Persons under an Administrator` },
  { style: "Normal", text: `"Protected Person"` },
  { style: "Normal", text: `A child or dependant registered by a guardian, who does not hold an account` },
  { style: "Normal", text: `"Child Alert"` },
  { style: "Normal", text: `A missing-person alert raised by a guardian for a Protected Person, shown as a pin on the map and sent to nearby users, where an image may be revealed on tap` },
  { style: "Normal", text: `"Subscription"` },
  { style: "Normal", text: `A paid recurring plan` },
  { style: "Heading2", text: `2. Eligibility and your account` },
  { style: "Normal", text: `2.1 You must be at least 16 to hold an account. Users aged 13–15 may hold a restricted linked account only within a Family Group, with verifiable guardian consent, and only where local law permits. Nobody under 13 may hold an account anywhere in the world.` },
  { style: "Normal", text: `2.2 You must give accurate registration information and keep it up to date.` },
  { style: "Normal", text: `2.3 You are responsible for your account credentials and for everything done through your account. Tell us immediately at admin@thewileyfox.com if you suspect unauthorised access.` },
  { style: "Normal", text: `2.4 One person, one account. You may not share, sell or transfer your account.` },
  { style: "Normal", text: `2.5 If you use the Services on behalf of a business or organisation, you confirm you have authority to bind it, and "you" includes that organisation.` },
  { style: "Heading2", text: `3. Licence to use the Services` },
  { style: "Normal", text: `3.1 We grant you a limited, personal, non-exclusive, non-transferable, revocable licence to use the Services for your own non-commercial use, subject to these Terms.` },
  { style: "Normal", text: `3.2 You may not:` },
  { style: "Normal", text: `copy, scrape, harvest, mine, spider or bulk-extract any part of the Services or the Safety Information;` },
  { style: "Normal", text: `reverse-engineer, decompile or attempt to derive our source code, algorithms or safety-scoring methodology;` },
  { style: "Normal", text: `use the Services or any data from them to train a machine-learning model without our written permission;` },
  { style: "Normal", text: `resell, sublicense or commercially exploit the Services or Safety Information;` },
  { style: "Normal", text: `use automated means to access the Services except a compliant search-engine crawler;` },
  { style: "Normal", text: `circumvent rate limits, access controls, geo-restrictions or security measures;` },
  { style: "Normal", text: `use the Services for anything unlawful, or in breach of any third-party rights.` },
  { style: "Normal", text: `3.3 We reserve all rights not expressly granted. "Wiley Fox", our logo, our design system and our safety-scoring methodology are our intellectual property.` },
  { style: "Heading2", text: `4. Safety Information — what it is and what it is not` },
  { style: "Normal", text: `This clause is central to the agreement between us. Please read it carefully.` },
  { style: "Normal", text: `4.1 Information only. Safety Information is provided for general information. It is not advice, a recommendation, an endorsement, an assurance, a prediction, or a professional risk assessment. It must not be relied upon as the sole basis for any decision about your safety, travel, accommodation or route.` },
  { style: "Normal", text: `4.2 Third-party source data. Crime and safety data is obtained from third-party public sources including data.police.uk and equivalent national bodies. We do not create, control, verify or audit it. It is frequently incomplete, delayed by weeks or months, inconsistently categorised across regions and countries, and reflects only reported crime. Coverage varies significantly by country and, within the UK, does not currently include Scotland. We give no warranty as to its accuracy, completeness, currency or fitness for any purpose.` },
  { style: "Normal", text: `4.3 Safety ratings are indicators, not verdicts. A rating is the output of a calculation applied to imperfect data. A "safe" rating does not mean an area is safe, and does not mean you will be safe there. Serious crime, accident, illness and harm occur in areas with low recorded crime. Equally, a low rating does not mean an area should be avoided.` },
  { style: "Normal", text: `4.4 No recommendation. We do not recommend, endorse, warrant or vouch for any country, city, region, neighbourhood, route, property, business or attraction shown in the Services. If you decide to enter or travel through any area, or to follow any route, you do so entirely at your own risk and on your own judgement.` },
  { style: "Normal", text: `4.5 Routing. Routes are generated automatically and do not account for road conditions, closures, terrain, weather, time of day, local events, accessibility needs, traffic law, or your personal circumstances. Always observe the law and your surroundings. Do not follow directions into danger.` },
  { style: "Normal", text: `4.6 Official sources take precedence. You should always consult official government travel advice — for UK travellers, gov.uk/foreign-travel-advice — local authorities, and your insurer, and follow their guidance over anything shown in the Services.` },
  { style: "Normal", text: `4.7 No professional relationship. Nothing in the Services constitutes legal, medical, security, insurance or travel advice, and no professional or advisory relationship arises between us.` },
  { style: "Heading2", text: `5. User Content` },
  { style: "Normal", text: `5.1 We do not fact-check. Pins, reports, photographs, reviews and comments are submitted by users. We do not verify, endorse or take responsibility for them. They may be inaccurate, incomplete, outdated, biased or deliberately false. Treat them as one person's unverified opinion.` },
  { style: "Normal", text: `5.2 Your responsibility. You are solely responsible for your Content, and you warrant that:` },
  { style: "Normal", text: `it is accurate to the best of your knowledge and submitted in good faith;` },
  { style: "Normal", text: `you own it or have all necessary rights to submit it;` },
  { style: "Normal", text: `it does not infringe anyone's intellectual property, privacy or other rights;` },
  { style: "Normal", text: `it does not identify or depict another adult without their consent, and does not depict any child except as permitted by clause 5.7;` },
  { style: "Normal", text: `it is not defamatory, harassing, threatening, discriminatory, obscene, or unlawful;` },
  { style: "Normal", text: `it does not target, disparage or make unfounded claims about any identifiable individual, business or community.` },
  { style: "Normal", text: `5.3 Licence to us. You keep ownership of your Content. You grant us a worldwide, non-exclusive, royalty-free, sublicensable licence to host, store, reproduce, adapt, publish and display it for the purpose of operating and promoting the Services. This licence ends when you delete the Content, except for copies retained in backups, in anonymised aggregate safety signals, or where we must retain it for legal or safety reasons.` },
  { style: "Normal", text: `5.4 Moderation and removal. We may remove any Content, suspend any account, and restrict any feature, at our discretion, without notice, where we consider it necessary. We do not carry out general monitoring of all Content, and the fact that Content remains published is not an endorsement of it. However, we do operate proactive automated screening of every uploaded image for child sexual abuse material and other unlawful content, and we act on reports as set out below. Nothing in this clause limits the duties we owe under the Online Safety Act 2023.` },
  { style: "Normal", text: `5.5 Reporting and takedown. Report unlawful or harmful Content through the in-app report function or to admin@thewileyfox.com.` },
  { style: "Normal", text: `Images of children, and any content suggesting a child is at risk, are treated as top priority and are reviewed within [24] hours, and removed immediately on a credible report pending review.` },
  { style: "Normal", text: `All other reports are assessed promptly and ordinarily within [72] hours.` },
  { style: "Normal", text: `Where a report concerns a statement about an identifiable person or business and you tell us you believe it is defamatory, we operate the process in the Defamation (Operators of Websites) Regulations 2013: we will contact the person who posted it within 48 hours of receiving a compliant notice, and follow the statutory timetable for their response, for removal, and for passing your details to them where they refuse removal. To use this process your notice must state your name, the words complained of, why they are defamatory, where they appear, and whether you consent to your details being passed on.` },
  { style: "Normal", text: `You may appeal any moderation decision by replying to our notice. We review appeals within [14] days, by a person not involved in the original decision.` },
  { style: "Normal", text: `5.6 Review authenticity. You must not post a review, rating or pin that is fake, incentivised, or written about a place or business you have no genuine experience of, and you must not offer or accept payment for one. We take reasonable and proportionate steps to detect and remove fake reviews, as required by the Digital Markets, Competition and Consumers Act 2024.` },
  { style: "Heading3", text: `5.7 Images of children — you must accept this clause separately` },
  { style: "Normal", text: `This is the most important rule on this platform. Read every word of it.` },
  { style: "Normal", text: `You must tick to accept this clause before you can upload any image. We record that acceptance, with the version and date.` },
  { style: "Normal", text: `5.7.1 The rule. You must not upload, post, pin, broadcast or otherwise submit any photograph, video or other image in which a child is identifiable. A child is anyone under 18. "Identifiable" includes a recognisable face, and it also includes an image that identifies a child in combination with anything else on screen — a school uniform, a name, a street, a house number, a vehicle registration.` },
  { style: "Normal", text: `5.7.2 The only exception — a Child Alert. You may include an image of a child only where all of the following are true:` },
  { style: "Normal", text: `the child is a Protected Person in your own Family Group;` },
  { style: "Normal", text: `you hold parental responsibility or lawful guardianship for that child;` },
  { style: "Normal", text: `you are raising an active Child Alert because that child is missing; and` },
  { style: "Normal", text: `you confirm, at the moment you raise the alert, that you want the image included.` },
  { style: "Normal", text: `There is no other circumstance in which an image of a child may be posted. You may not post an image of someone else's child even if you believe you have their guardian's permission, and even if the guardian has asked you to.` },
  { style: "Normal", text: `5.7.3 Incidental images. If a child appears incidentally in a photograph of a street, building or area, do not upload it. Take a different photograph. We may remove any image containing a child regardless of how or why it was taken.` },
  { style: "Normal", text: `5.7.4 How a Child Alert image is shown. Where you include an image in a Child Alert:` },
  { style: "Normal", text: `the alert appears as a pin on the map and as a notification to users in the surrounding area;` },
  { style: "Normal", text: `the image is not displayed automatically. A user must actively tap through a warning notice before it is revealed;` },
  { style: "Normal", text: `that notice tells them the image shows a missing child, that it is shared only to help find that child, and that any other use — including saving, copying, resharing or publishing it — may be a criminal offence;` },
  { style: "Normal", text: `every reveal is logged, and the log is available to you and to the police;` },
  { style: "Normal", text: `the image is removed from the Services the moment you cancel the alert, and automatically on expiry under clause 6.4.` },
  { style: "Normal", text: `5.7.5 What you accept when you include an image. You accept that once an image has been revealed to another user, we cannot recall it. A user may photograph their own screen. We can remove the image from Wiley Fox; we cannot remove it from the internet or from someone's device. Please think carefully before including a photograph of your child, and consider whether a written description would be enough.` },
  { style: "Normal", text: `5.7.6 If you scan, see or receive a child's image through the Services, you may use it only to help find or return that child. Saving it, copying it, resharing it, publishing it, or using it for any other purpose whatsoever is prohibited, is a breach of these Terms, may breach data protection law, and may be a criminal offence.` },
  { style: "Normal", text: `5.7.7 Child sexual abuse material — absolute prohibition. You must never upload, request, share, link to or solicit any image or material that sexually exploits or abuses a child, or any content that sexualises a child, whether real, drawn, edited or artificially generated. There is no exception, no context and no defence for this.` },
  { style: "Normal", text: `Where we identify such material, or content that appears to constitute grooming or child sexual exploitation, we will, without notifying you and without waiting for a report:` },
  { style: "Normal", text: `remove it and permanently ban every account involved;` },
  { style: "Normal", text: `preserve the material and all associated account, device and log data as evidence;` },
  { style: "Normal", text: `report it to the police and to the Internet Watch Foundation, and to the National Center for Missing & Exploited Children where a US nexus exists;` },
  { style: "Normal", text: `cooperate fully with any resulting investigation, including by disclosing your identity, contact details, IP addresses and activity history.` },
  { style: "Normal", text: `5.7.8 Breach. Any breach of clause 5.7 is a material breach of these Terms. It results in immediate permanent removal of your account without refund, and, where appropriate, referral to the police and to any relevant safeguarding authority.` },
  { style: "Normal", text: `5.8 Prohibited uses. You must not use the Services to track, surveil, harass, stalk, intimidate, dox, defraud, groom or endanger any person; to post another person's private information; to encourage vigilantism; to create false emergency alerts; to raise a Child Alert that is not genuine; or to make claims about an area that are motivated by discrimination rather than observation. Breach of this clause is grounds for immediate permanent ban and, where appropriate, referral to the police.` },
  { style: "Heading2", text: `6. QR tags, Family Groups and Protected Persons` },
  { style: "Normal", text: `6.1 Guardian warranties. If you register a Protected Person, you warrant that you hold parental responsibility or lawful guardianship for that person, and that you are entitled to provide their data and to make decisions about publishing it. You indemnify us against any claim arising from a breach of this warranty, including any claim by another parent, guardian or family member.` },
  { style: "Normal", text: `6.2 You control what is published. A scan page shows only the information you have selected. It is your responsibility to keep that information accurate, current and appropriate, and to review it regularly — particularly medical information and emergency contacts.` },
  { style: "Normal", text: `6.3 No guarantee of reunification or response. A QR tag depends on a stranger finding the item or person, choosing to scan it, having a working device and internet connection, and choosing to act. We do not and cannot guarantee that a lost item or person will be found, returned or reunited, or that any scan, alert or message will be delivered, received, seen or acted upon.` },
  { style: "Normal", text: `6.4 Community broadcasts and Child Alerts. Where you broadcast a lost-person alert:` },
  { style: "Normal", text: `you confirm you have the authority and consent to share what you include, including any photograph;` },
  { style: "Normal", text: `where the alert concerns a child, clause 5.7 applies in full and the image is shown only behind a tap-to-reveal notice;` },
  { style: "Normal", text: `you accept that once information leaves our platform we cannot recall it, and other users may screenshot or reshare it;` },
  { style: "Normal", text: `you accept that a broadcast is not a substitute for contacting the police, and you should contact them first;` },
  { style: "Normal", text: `we may decline, limit or withdraw a broadcast at our discretion.` },
  { style: "Normal", text: `6.5 Medical information. Medical profiles are a convenience for sharing information you choose to share. Wiley Fox is not a medical device, does not provide medical advice, and is not regulated as a medical product. We do not verify, interpret, update or validate medical information. Emergency responders may not scan a tag, may not have a device, or may rely on their own protocols. Do not rely on a Wiley Fox wristband as your only means of communicating critical medical information.` },
  { style: "Normal", text: `6.6 SOS. An SOS alert is a message to other Wiley Fox users. It is not a call to the emergency services, is not monitored by us, and may fail for reasons including no signal, low battery, device failure, no nearby users, or nobody choosing to respond. We accept no responsibility for any failure of an SOS alert to be sent, received, or acted upon.` },
  { style: "Normal", text: `6.7 Scanners. If you scan someone else's tag, you must use the information only to help return the item or assist the person. Any other use — including retaining, copying, publishing, or contacting the person for an unrelated purpose — is prohibited, may breach data protection law, and may be a criminal offence.` },
  { style: "Normal", text: `6.8 Blocking. Every user can permanently block any other user or scanner. We may retain limited records of blocked interactions for safety purposes.` },
  { style: "Heading2", text: `7. Third-party bookings, links and services` },
  { style: "Normal", text: `7.1 We are an introducer, not the supplier. Where the Services show accommodation, attractions, tours, transport, insurance or other third-party offerings, we are providing a link. Any booking or purchase is a contract between you and that third party, on their terms, and we are not a party to it.` },
  { style: "Normal", text: `7.2 Not our responsibility. We are not responsible for the availability, quality, safety, legality, pricing, delivery, cancellation, refund or performance of any third-party product or service, or for any act or omission of the provider.` },
  { style: "Normal", text: `7.3 Complaints, changes, cancellations and refunds relating to a third-party booking must be raised directly with that provider, under their terms. We cannot amend, cancel or refund a booking made with a third party, and we cannot intervene in a dispute with them. We will, on request, provide any booking reference we hold.` },
  { style: "Normal", text: `7.4 Affiliate disclosure. We earn a commission on some bookings made through our links. This never increases the price you pay, and it never affects the Safety Information we display. Where a listing is commercial or sponsored, we label it.` },
  { style: "Normal", text: `7.5 Package travel. We do not sell package holidays or linked travel arrangements, and we are not an ATOL holder or a member of ABTA. If you combine travel services yourself, you may not benefit from the protections of the Package Travel and Linked Travel Arrangements Regulations 2018.` },
  { style: "Normal", text: `7.6 Third-party links generally. We do not control and are not responsible for third-party websites, apps or content linked from the Services.` },
  { style: "Heading2", text: `8. Products — buying merchandise` },
  { style: "Normal", text: `This section applies where you buy physical Products from us.` },
  { style: "Normal", text: `8.1 Contract formation. Your order is an offer. A contract forms when we send you a dispatch confirmation. If we cannot fulfil an order — including because of an obvious pricing error that you could reasonably have recognised as an error — we may cancel it and refund you in full.` },
  { style: "Normal", text: `8.2 Pricing. Prices include UK VAT where applicable and exclude delivery unless stated. For deliveries outside the UK, you are the importer of record and are responsible for any customs duties, import VAT and handling fees. These are not included in our prices and are not refundable by us.` },
  { style: "Normal", text: `8.3 Fulfilment. Products are made and shipped by print-on-demand and fulfilment partners. Delivery estimates are estimates, not guarantees. Risk passes to you on delivery; title passes on full payment.` },
  { style: "Normal", text: `8.4 Your right to cancel (UK/EU consumers). You have 14 days from the day you receive the goods to cancel without giving a reason, and a further 14 days to return them. Refunds are made within 14 days of us receiving the goods back or your proof of return.` },
  { style: "Normal", text: `Important exception: under regulation 28(1)(b) of the Consumer Contracts (Information, Cancellation and Additional Charges) Regulations 2013, the right to cancel does not apply to goods made to your specification or clearly personalised. Most Wiley Fox QR tags, wristbands and labels are personalised to you at the point of manufacture, so once production has begun they cannot be cancelled or returned unless faulty. We will tell you clearly at checkout which items this applies to.` },
  { style: "Normal", text: `8.5 Faulty or misdescribed goods. Nothing in these Terms affects your statutory rights. Under the Consumer Rights Act 2015, goods must be of satisfactory quality, fit for purpose and as described. If they are not, you may be entitled to a repair, replacement, or a full or partial refund. Contact admin@thewileyfox.com.` },
  { style: "Normal", text: `8.6 Product limitations. QR tags are printed consumer products. They can be lost, removed, obscured, soiled, faded, torn or damaged, and printed codes degrade with wear, washing and sunlight. Check your tags regularly and replace them when worn. A damaged or unscannable tag will not work, and we are not liable for a failure to reunite caused by physical damage to a tag.` },
  { style: "Normal", text: `8.7 Not safety equipment. Our Products are identification aids. They are not personal protective equipment, medical devices, tracking devices, alarms or child-restraint products, and must not be relied on as such. They do not physically prevent a child from becoming separated from you. Adult supervision of children is never replaced by a Wiley Fox product.` },
  { style: "Heading2", text: `9. Subscriptions and payment` },
  { style: "Normal", text: `9.1 Paid plans are billed in advance, monthly or annually, and renew automatically until cancelled.` },
  { style: "Normal", text: `9.2 Cancelling. You can cancel at any time in the app or, for App Store / Google Play subscriptions, through your store account. Cancellation takes effect at the end of the current billing period. You keep access until then.` },
  { style: "Normal", text: `9.3 Refunds. UK and EU consumers have a 14-day cancellation right for digital services. If you ask us to start the service immediately within that period, you acknowledge you lose the right to cancel once the service is fully performed; where it is partly performed we may charge a proportionate amount. Beyond that, subscription fees are non-refundable except where required by law or where we have materially failed to provide the service. Store-billed subscriptions are refunded by Apple or Google under their policies.` },
  { style: "Normal", text: `9.4 Price changes. We will give at least 30 days' notice of a price increase before it applies to you, and you may cancel before it takes effect.` },
  { style: "Normal", text: `9.5 Free trials and renewal reminders. If offered, a trial converts to a paid subscription unless cancelled before it ends. In line with the Digital Markets, Competition and Consumers Act 2024 we will remind you in good time before a free trial converts, and before each annual renewal, telling you what you will be charged, when, and how to cancel. Cancelling is always at least as easy as subscribing was.` },
  { style: "Normal", text: `9.6 Advertising on the free tier. The free tier is supported by advertising. What this means for your data is set out in our Privacy Policy. We do not serve personalised or behavioural advertising to any account belonging to a person under 18, and we never use Safety Information, location history, health data, Protected Person data or Child Alert content to target advertising to anyone. Premium is ad-free.` },
  { style: "Normal", text: `9.7 Failed payment. We may suspend paid features if payment fails, after notifying you and allowing a reasonable time to fix it.` },
  { style: "Normal", text: `9.8 Taxes. Prices include VAT or local sales tax where we are required to charge it. Business customers outside the UK may be responsible for accounting for tax under the reverse charge.` },
  { style: "Heading2", text: `10. Availability and changes` },
  { style: "Normal", text: `10.1 We aim to keep the Services available but do not guarantee uninterrupted or error-free operation. We may suspend the Services for maintenance, security or upgrades, with notice where practicable.` },
  { style: "Normal", text: `10.2 We may add, change, restrict or withdraw features. Where a change materially reduces a paid feature you rely on, we will give reasonable notice and you may cancel and receive a pro-rata refund for the unused period.` },
  { style: "Normal", text: `10.3 The Services depend on your device, operating system, internet connection and third-party providers, and on permissions you grant. We are not responsible for failures caused by any of these.` },
  { style: "Normal", text: `10.4 Geographic coverage varies. Data quality, feature availability and coverage differ by country and region, and some features may be unavailable where local law restricts them.` },
  { style: "Heading2", text: `11. Suspension and termination` },
  { style: "Normal", text: `11.1 By you. You may close your account at any time in Settings → Account. Deletion is handled as set out in our Privacy Policy.` },
  { style: "Normal", text: `11.2 By us. We may suspend or terminate your account, immediately and without refund, if you materially breach these Terms — in particular the images-of-children provisions in clause 5.7, the prohibited-use provisions in clause 5.8, or the guardian warranties in clause 6.1 — or where we reasonably believe it necessary to protect other users, a child, a vulnerable adult, or Wiley Fox.` },
  { style: "Normal", text: `11.3 Where practicable we will tell you why and give you an opportunity to respond. We may act without notice where there is a risk of harm, a legal requirement, or a risk of evidence being destroyed.` },
  { style: "Normal", text: `11.4 On termination, your licence ends and your active QR tags stop working. Clauses that by their nature should survive — including 4, 5.2, 5.3, 5.7, 6.1, 12, 13, 14 and 17 — survive termination.` },
  { style: "Heading2", text: `12. Our liability` },
  { style: "Normal", text: `Nothing in this clause limits liability that cannot lawfully be limited.` },
  { style: "Normal", text: `12.1 What we never exclude. We do not exclude or limit our liability for:` },
  { style: "Normal", text: `death or personal injury caused by our negligence;` },
  { style: "Normal", text: `fraud or fraudulent misrepresentation;` },
  { style: "Normal", text: `breach of the terms implied by sections 9–11 of the Consumer Rights Act 2015 or sections 12–15 of the Sale of Goods Act 1979;` },
  { style: "Normal", text: `defective products under the Consumer Protection Act 1987;` },
  { style: "Normal", text: `any other liability that cannot be excluded under applicable law.` },
  { style: "Normal", text: `12.2 If you are a consumer. We are responsible for loss or damage you suffer that is a foreseeable result of our breach of these Terms or our failure to use reasonable care and skill. We are not responsible for loss or damage that is not foreseeable. Your statutory rights are unaffected, and nothing here is intended to be an unfair term under Part 2 of the Consumer Rights Act 2015.` },
  { style: "Normal", text: `12.3 What we are not liable for. Subject to clause 12.1, we are not liable for:` },
  { style: "Normal", text: `any decision you make about where to travel, stay, walk, drive or go, or any consequence of that decision;` },
  { style: "Normal", text: `the accuracy, completeness or currency of Safety Information or third-party data;` },
  { style: "Normal", text: `any Content posted by another user, or any reliance you place on it;` },
  { style: "Normal", text: `any act or omission of another user, a scanner, a member of the public, or a third-party provider;` },
  { style: "Normal", text: `any crime, accident, injury, illness, loss or damage occurring in any area, however that area is rated in the Services;` },
  { style: "Normal", text: `failure of an SOS alert, community broadcast, notification or message to be sent, delivered, received, seen or acted upon;` },
  { style: "Normal", text: `failure to locate, recover or reunite any lost item, child or dependant;` },
  { style: "Normal", text: `any failure caused by your device, connection, permissions settings, or a third-party platform;` },
  { style: "Normal", text: `any third-party booking, product or service;` },
  { style: "Normal", text: `loss of profit, revenue, business, opportunity, goodwill, anticipated saving, or data — in each case where you are using the Services for business purposes.` },
  { style: "Normal", text: `12.4 Cap on liability. Subject to clause 12.1, our total aggregate liability arising out of or in connection with these Terms and the Services, whether in contract, tort (including negligence), breach of statutory duty or otherwise, is limited to the greater of (a) the total amount you paid us in the 12 months before the event giving rise to the claim, and (b) £100.` },
  { style: "Normal", text: `12.5 Business users. If you use the Services for any business purpose, clause 12.2 does not apply to you, the exclusions in 12.3 apply in full, and you agree the cap in 12.4 is reasonable given the nature of the Services and the fact that Safety Information is provided without charge and without verification.` },
  { style: "Normal", text: `12.6 Allocation of risk. You acknowledge that the pricing of the Services reflects this allocation of risk, and that we would not be able to provide safety information at all if we accepted liability for the decisions users make on the basis of it.` },
  { style: "Heading2", text: `13. Indemnity` },
  { style: "Normal", text: `You agree to indemnify us, and our officers and employees, against all claims, liabilities, losses, damages and reasonable costs (including legal fees) arising from:` },
  { style: "Normal", text: `your breach of these Terms or of applicable law;` },
  { style: "Normal", text: `your Content, including any claim that it is defamatory, infringing or a breach of privacy;` },
  { style: "Normal", text: `any image of a child you posted in breach of clause 5.7, including any claim brought by that child, their guardian, or a regulator;` },
  { style: "Normal", text: `your registration of a Protected Person where you did not hold the authority you warranted in clause 6.1;` },
  { style: "Normal", text: `your misuse of information obtained by scanning another user's tag;` },
  { style: "Normal", text: `any claim by a third party arising from your use of the Services.` },
  { style: "Normal", text: `This clause does not apply to consumers except in respect of deliberate or reckless breaches.` },
  { style: "Heading2", text: `14. Governing law and disputes` },
  { style: "Normal", text: `14.1 These Terms and any dispute arising from them are governed by the law of England and Wales.` },
  { style: "Normal", text: `14.2 The courts of England and Wales have exclusive jurisdiction, except that:` },
  { style: "Normal", text: `if you are a consumer resident in the UK, the EU, or another country whose law gives you the right to bring proceedings locally, you may bring proceedings in your country of residence, and you retain the benefit of any mandatory consumer protections of that country that cannot be derogated from by agreement;` },
  { style: "Normal", text: `we may bring proceedings in the courts of your country of residence to enforce these Terms.` },
  { style: "Normal", text: `14.3 Complaints first. Please contact us at admin@thewileyfox.com before starting proceedings. We aim to acknowledge within 5 working days and resolve within 30 days.` },
  { style: "Normal", text: `14.4 EU consumers may also use the European Commission's Online Dispute Resolution platform.` },
  { style: "Normal", text: `14.5 Nothing in this clause requires you to waive any non-waivable right, and we do not require consumers to arbitrate.` },
  { style: "Heading2", text: `15. Changes to these Terms` },
  { style: "Normal", text: `We may update these Terms. For material changes we will give at least 30 days' notice by email and in-app. If you do not accept a change, you may close your account before it takes effect and, if you have paid for a Subscription, receive a pro-rata refund for the unused period. Continuing to use the Services after the change takes effect means you accept it. Archived versions are at thewileyfox.com/legal/archive.` },
  { style: "Heading2", text: `16. App store terms` },
  { style: "Normal", text: `16.1 Apple. These Terms are between you and Wiley Fox, not Apple. Apple has no obligation to provide maintenance or support. If the app fails to conform to any applicable warranty, you may notify Apple for a refund of the purchase price; otherwise Apple has no warranty obligation. Apple is not responsible for any claims relating to the app, including product liability, regulatory non-compliance, or intellectual property claims. Apple and its subsidiaries are third-party beneficiaries of these Terms and may enforce them against you. You confirm you are not located in a country subject to a US Government embargo and are not on any US restricted-party list.` },
  { style: "Normal", text: `16.2 Google. Your use of the app from Google Play is also subject to the Google Play Terms of Service.` },
  { style: "Heading2", text: `17. General` },
  { style: "Normal", text: `17.1 Entire agreement. These Terms and the Privacy Policy are the whole agreement between us on this subject and replace any previous version. Nothing here excludes liability for fraudulent misrepresentation.` },
  { style: "Normal", text: `17.2 Severance. If any provision is found unenforceable, it is modified to the minimum extent necessary or severed, and the rest continues in force.` },
  { style: "Normal", text: `17.3 No waiver. A delay in enforcing a right is not a waiver of it.` },
  { style: "Normal", text: `17.4 Assignment. You may not assign your rights. We may assign or transfer ours on notice to you, provided your rights are not adversely affected.` },
  { style: "Normal", text: `17.5 Third-party rights. Except as set out in clause 16.1, nobody other than you and us has rights under these Terms (Contracts (Rights of Third Parties) Act 1999).` },
  { style: "Normal", text: `17.6 Force majeure. We are not liable for failure caused by events beyond our reasonable control, including internet or platform outages, failure of third-party data sources, natural events, war, civil unrest, or government action.` },
  { style: "Normal", text: `17.7 Notices. We will contact you by email or in-app notification. You should contact us at admin@thewileyfox.com.` },
  { style: "Heading2", text: `18. Contact` },
  { style: "Normal", text: `Wiley Fox Mapping Limited [REGISTERED ADDRESS] Company number 17172765` },
  { style: "Normal", text: `General & complaints: admin@thewileyfox.com Privacy & data rights: privacy@thewileyfox.com` },
  { style: "Normal", text: `Travel with more confidence. Never with less care.` },
];

export default function TermsPage() {
  return (
    <LegalPageLayout
      title="Terms & Conditions"
      lastUpdated="4 August 2026"
      version="1.1"
      content={CONTENT}
      otherLink={{ href: '/privacy-policy', label: 'Privacy Policy' }}
    />
  );
}
