
auth.token=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

defaults.org=thewileyfox
defaults.project=mobile

defaults.url=https://sentry.io/
